name: 'AWS Credentials via OIDC'
description: 'Configure AWS credentials using OIDC and verify access'

inputs:
  role_arn:
    description: 'AWS IAM Role ARN to assume'
    required: true
  aws_region:
    description: 'AWS region'
    required: true

outputs:
  aws-access-key-id:
    description: 'AWS Access Key ID'
    value: ${{ steps.creds.outputs.aws-access-key-id }}
  aws-secret-access-key:
    description: 'AWS Secret Access Key'
    value: ${{ steps.creds.outputs.aws-secret-access-key }}
  aws-session-token:
    description: 'AWS Session Token'
    value: ${{ steps.creds.outputs.aws-session-token }}

runs:
  using: 'composite'
  steps:
    - name: Configure AWS Credentials
      id: creds
      uses: aws-actions/configure-aws-credentials@v5.1.1
      with:
        role-to-assume: ${{ inputs.role_arn }}
        aws-region: ${{ inputs.aws_region }}
        role-session-name: "oidc-session"
        output-credentials: true

    - name: Verify Caller Identity
      shell: bash
      run: aws sts get-caller-identity
